# Generated by Django 5.0.4 on 2024-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
