# Generated by Django 5.0.4 on 2024-04-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_restf', '0003_alter_ticket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='device',
            field=models.CharField(default='unknows', max_length=50),
        ),
    ]
